
# ??? ??
spring:
  datasource:
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:mariadb://localhost:3308/lol_dp
      username: lol_dp
      password: 1234

  # ?? ?? ?? ??? ??
  devtools:
    restart:
      enabled: 'false'
    livereload:
      enabled: 'true'

  # ???? ?? OFF
  thymeleaf:
    cache: 'false'

  # JPA
  jpa:
    database: mysql
    dialect: org.hibernate.dialect.MariaDBDialect
    generate-ddl: 'false'
    show-sql: 'true'
    open-in-view: 'false'
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: 'true'
        use_sql_comments: 'true'
        default_batch_fetch_size: '100'

  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            user-name-attribute: id
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            user-name-attribute: sub
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

        registration:
          kakao:
            client-name: kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-id: [클라이언트 아이디]
            client-secret: [클라이언트 보안 비밀번호]
            client-authentication-method: client_secret_post
            scope: account_email
          google:
            client-name: google
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            client-id: [클라이언트 아이디]
            client-secret: [클라이언트 보안 비밀번호]
            client-authentication-method: client_secret_post
            scope: profile,email
          naver:
            client-id: [클라이언트 아이디]
            client-secret: [클라이언트 보안 비밀번호]
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope: name,email,nickname
            client-name: naver

logging:
  level:
    org:
      springframework:
        transaction: DEBUG
        security: TRACE

mail:
  smtp:
    auth: true
    starttls:
      required: true
      enable: true
    socketFactory:
      class: javax.net.ssl.SSLSocketFactory
      fallback: false
      port: 465
    port: 465

myapp:
  custom:
    mail:
      sender:
        username: [네이버 아이디]
        password: [네이버 비밀번호]
        host: smtp.naver.com
        mailFrom: [인증키 보낼 이메일 주소]
        mailFromName: lol_dp

