
# ??? ??
spring:
  datasource:
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:mariadb://localhost:3306/lol_dp
      username: lol_dp
      password: 1234

  # ?? ?? ?? ??? ??
  devtools:
    restart:
      enabled: 'false'
    livereload:
      enabled: 'true'

  # ???? ?? OFF
  thymeleaf:
    cache: 'false'

  # JPA
  jpa:
    database: mysql
    dialect: org.hibernate.dialect.MariaDBDialect
    generate-ddl: 'false'
    show-sql: 'true'
    open-in-view: 'false'
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: 'true'
        use_sql_comments: 'true'
        default_batch_fetch_size: '100'


logging:
  level:
    org:
      springframework:
        transaction: DEBUG
        security: TRACE

